package fr.pivot.collaboratif.whiteboard.canvas;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a connector linking two {@link Card}s on the same board (US08.7.1).
 *
 * <p>Created and deleted exclusively over STOMP ({@code connection:create}/
 * {@code connection:delete}, see {@link CanvasActionService}) — there is no dedicated REST route
 * for connector mutations, mirroring the reference whiteboard's design (parity spec §3.6).
 *
 * <p>Default field values ({@code shape} = {@code curved}, {@code arrow} = {@code none},
 * {@code dashed} = {@code false}, {@code width} = 2, {@code label}/{@code color} = {@code null})
 * match the reference whiteboard's connector defaults exactly (parity spec §7) and are fixed at
 * creation time — not user-selectable there; styling is a separate partial-patch mutation
 * ({@code connection:update}, US08.7.2, see
 * {@link fr.pivot.collaboratif.whiteboard.canvas.CanvasActionService#handleConnectionUpdate}).
 *
 * <p>{@code fromId}/{@code toId} reference {@link Card} rows with {@code ON DELETE CASCADE} —
 * deleting either endpoint card removes this connector automatically, so
 * {@link CanvasActionService#handleConnectionDelete} must tolerate an id already gone via
 * cascade (idempotent delete, same convention as {@link CardRepository#deleteByIdAndBoardId}).
 */
@Entity
@Table(name = "card_connection", schema = "collaboratif")
public class CardConnection {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this connector belongs to; cascades on board deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "board_id", nullable = false, updatable = false)
    private UUID boardId;

    /** Tenant owning the board this connector belongs to — for tenant-scoped queries. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Source card id; cascades on the source card's deletion. */
    @Column(name = "from_id", nullable = false, updatable = false)
    private UUID fromId;

    /** Target card id; cascades on the target card's deletion. */
    @Column(name = "to_id", nullable = false, updatable = false)
    private UUID toId;

    /** Optional connector label; {@code null} until styled (US08.7.2). */
    @Column(name = "label")
    private String label;

    /** Optional connector colour (hex); {@code null} until styled (US08.7.2). */
    @Column(name = "color", length = 20)
    private String color;

    /** Connector line shape; defaults to {@code curved}. */
    @Column(name = "shape", nullable = false, length = 20)
    private String shape = "curved";

    /** Connector arrowhead style; defaults to {@code none}. */
    @Column(name = "arrow", nullable = false, length = 20)
    private String arrow = "none";

    /**
     * Whether the connector line is dashed; defaults to {@code false}.
     *
     * <p>Legacy field superseded by {@link #lineStyle} (US08.7.2 style extension). Kept for
     * back-compat and derived-in-sync on write: {@link #setLineStyle} recomputes it as
     * {@code !"solid".equals(lineStyle)}.
     */
    @Column(name = "dashed", nullable = false)
    private boolean dashed;

    /** Connector line stroke width; defaults to 2. */
    @Column(name = "width", nullable = false)
    private int width = 2;

    /**
     * Connector line style; one of {@code solid}/{@code dashed}/{@code dotted}, default
     * {@code solid} (US08.7.2 style extension). Supersedes the boolean {@link #dashed}, which is
     * kept derived-in-sync on write (see {@link #setLineStyle}).
     */
    @Column(name = "line_style", nullable = false, length = 20)
    private String lineStyle = "solid";

    /**
     * Connector head cap at the source end; one of
     * {@code none}/{@code arrow}/{@code triangle}/{@code circle}/{@code diamond}, default
     * {@code none} (US08.7.2 style extension). Together with {@link #endCap} it supersedes the
     * legacy {@link #arrow} field, which is kept derived-in-sync on write (see {@link #setStartCap}).
     */
    @Column(name = "start_cap", nullable = false, length = 20)
    private String startCap = "none";

    /**
     * Connector head cap at the target end; one of
     * {@code none}/{@code arrow}/{@code triangle}/{@code circle}/{@code diamond}, default
     * {@code none} (US08.7.2 style extension). Together with {@link #startCap} it supersedes the
     * legacy {@link #arrow} field, which is kept derived-in-sync on write (see {@link #setEndCap}).
     */
    @Column(name = "end_cap", nullable = false, length = 20)
    private String endCap = "none";

    /** Timestamp when this connector was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected CardConnection() {
    }

    /**
     * Creates a new connector between two cards, taking every style field's fixed default
     * (parity spec §7) — style is never client-supplied at creation time.
     *
     * @param boardId  the owning board's UUID
     * @param tenantId the owning board's tenant id
     * @param fromId   the source card's UUID
     * @param toId     the target card's UUID
     * @param now      timestamp used for {@code createdAt}
     */
    public CardConnection(
            final UUID boardId,
            final Long tenantId,
            final UUID fromId,
            final UUID toId,
            final Instant now) {
        this.boardId = boardId;
        this.tenantId = tenantId;
        this.fromId = fromId;
        this.toId = toId;
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not
     * already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the connector's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning board's identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the owning tenant's identifier.
     *
     * @return the tenant id
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the source card's identifier.
     *
     * @return the source card UUID
     */
    public UUID getFromId() {
        return fromId;
    }

    /**
     * Returns the target card's identifier.
     *
     * @return the target card UUID
     */
    public UUID getToId() {
        return toId;
    }

    /**
     * Returns the connector label.
     *
     * @return the label, or {@code null} if unset
     */
    public String getLabel() {
        return label;
    }

    /**
     * Returns the connector colour.
     *
     * @return the hex colour, or {@code null} if unset
     */
    public String getColor() {
        return color;
    }

    /**
     * Returns the connector line shape.
     *
     * @return the shape
     */
    public String getShape() {
        return shape;
    }

    /**
     * Returns the connector arrowhead style.
     *
     * @return the arrow style
     */
    public String getArrow() {
        return arrow;
    }

    /**
     * Returns whether the connector line is dashed.
     *
     * @return {@code true} if dashed
     */
    public boolean isDashed() {
        return dashed;
    }

    /**
     * Returns the connector line stroke width.
     *
     * @return the width
     */
    public int getWidth() {
        return width;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the connector label (US08.7.2, {@code connection:update}).
     *
     * @param label the new label, or {@code null} to clear it
     */
    public void setLabel(final String label) {
        this.label = label;
    }

    /**
     * Sets the connector colour (US08.7.2, {@code connection:update}).
     *
     * @param color the new hex colour, or {@code null} to clear it
     */
    public void setColor(final String color) {
        this.color = color;
    }

    /**
     * Sets the connector line shape (US08.7.2, {@code connection:update}). Callers must
     * validate the value against the applicative whitelist before calling this setter — see
     * {@link fr.pivot.collaboratif.whiteboard.canvas.CanvasActionService#handleConnectionUpdate}.
     *
     * @param shape the new shape
     */
    public void setShape(final String shape) {
        this.shape = shape;
    }

    /**
     * Sets the connector arrowhead style (US08.7.2, {@code connection:update}). Callers must
     * validate the value against the applicative whitelist before calling this setter — see
     * {@link fr.pivot.collaboratif.whiteboard.canvas.CanvasActionService#handleConnectionUpdate}.
     *
     * @param arrow the new arrowhead style
     */
    public void setArrow(final String arrow) {
        this.arrow = arrow;
    }

    /**
     * Sets whether the connector line is dashed (US08.7.2, {@code connection:update}).
     *
     * @param dashed the new dashed flag
     */
    public void setDashed(final boolean dashed) {
        this.dashed = dashed;
    }

    /**
     * Sets the connector line stroke width (US08.7.2, {@code connection:update}).
     *
     * @param width the new stroke width
     */
    public void setWidth(final int width) {
        this.width = width;
    }

    /**
     * Returns the connector line style ({@code solid}/{@code dashed}/{@code dotted}).
     *
     * @return the line style
     */
    public String getLineStyle() {
        return lineStyle;
    }

    /**
     * Returns the source-end head cap.
     *
     * @return the start cap
     */
    public String getStartCap() {
        return startCap;
    }

    /**
     * Returns the target-end head cap.
     *
     * @return the end cap
     */
    public String getEndCap() {
        return endCap;
    }

    /**
     * Sets the connector line style (US08.7.2 style extension, {@code connection:update}) and
     * keeps the legacy {@link #dashed} flag derived-in-sync: {@code dashed = !"solid".equals(lineStyle)}.
     * Callers must validate the value against the applicative whitelist before calling this setter
     * — see {@link fr.pivot.collaboratif.whiteboard.canvas.CanvasActionService#handleConnectionUpdate}.
     *
     * @param lineStyle the new line style
     */
    public void setLineStyle(final String lineStyle) {
        this.lineStyle = lineStyle;
        this.dashed = !"solid".equals(lineStyle);
    }

    /**
     * Sets the source-end head cap (US08.7.2 style extension, {@code connection:update}) and keeps
     * the legacy {@link #arrow} field derived-in-sync (see {@link #deriveArrow}). Callers must
     * validate the value against the applicative whitelist before calling this setter — see
     * {@link fr.pivot.collaboratif.whiteboard.canvas.CanvasActionService#handleConnectionUpdate}.
     *
     * @param startCap the new start cap
     */
    public void setStartCap(final String startCap) {
        this.startCap = startCap;
        this.arrow = deriveArrow(startCap, this.endCap);
    }

    /**
     * Sets the target-end head cap (US08.7.2 style extension, {@code connection:update}) and keeps
     * the legacy {@link #arrow} field derived-in-sync (see {@link #deriveArrow}). Callers must
     * validate the value against the applicative whitelist before calling this setter — see
     * {@link fr.pivot.collaboratif.whiteboard.canvas.CanvasActionService#handleConnectionUpdate}.
     *
     * @param endCap the new end cap
     */
    public void setEndCap(final String endCap) {
        this.endCap = endCap;
        this.arrow = deriveArrow(this.startCap, endCap);
    }

    /**
     * Derives the legacy {@code arrow} value from the two head caps, best-effort: both caps
     * {@code arrow} → {@code both}; only start → {@code start}; only end → {@code end}; otherwise
     * {@code none}. Non-{@code arrow} caps (triangle/circle/diamond) have no legacy {@code arrow}
     * equivalent and collapse to {@code none} on that end.
     *
     * @param start the source-end cap
     * @param end   the target-end cap
     * @return the derived legacy arrow value
     */
    private static String deriveArrow(final String start, final String end) {
        boolean startArrow = "arrow".equals(start);
        boolean endArrow = "arrow".equals(end);
        if (startArrow && endArrow) {
            return "both";
        }
        if (startArrow) {
            return "start";
        }
        if (endArrow) {
            return "end";
        }
        return "none";
    }
}
