package fr.pivot.collaboratif.whiteboard.notification;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing an in-app notification delivered to a single recipient (US08.2.5).
 *
 * <p>Notifications are the in-app channel for board-sharing events ({@link NotificationType}).
 * Sending a transactional e-mail is out of scope — the recipient is always an existing platform
 * user of the same tenant as the board. Rows are tenant-scoped and reference the acting user and
 * the board involved; the human-readable {@code body} is composed server-side in French.
 */
@Entity
@Table(name = "notification", schema = "collaboratif")
public class Notification {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant the notification belongs to ({@code public.tenants.id}). */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** User the notification is delivered to ({@code public.users.id}). */
    @Column(name = "recipient_user_id", nullable = false)
    private Long recipientUserId;

    /** User whose action triggered the notification ({@code public.users.id}). */
    @Column(name = "actor_user_id", nullable = false)
    private Long actorUserId;

    /** Board the notification relates to, or {@code null} if not board-scoped. */
    @Column(name = "board_id")
    private UUID boardId;

    /** The notification type. */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 30)
    private NotificationType type;

    /** Human-readable French body of the notification. */
    @Column(name = "body", nullable = false)
    private String body;

    /** Timestamp when the notification was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp when the recipient read the notification, or {@code null} while unread. */
    @Column(name = "read_at")
    private Instant readAt;

    /** No-arg constructor required by JPA. */
    protected Notification() {
    }

    /**
     * Creates a new unread notification.
     *
     * @param tenantId        the recipient/board tenant's {@code public.tenants.id}
     * @param recipientUserId the recipient's {@code public.users.id}
     * @param actorUserId     the acting user's {@code public.users.id}
     * @param boardId         the related board UUID, or {@code null}
     * @param type            the notification type
     * @param body            the human-readable French body
     */
    public Notification(
            final Long tenantId,
            final Long recipientUserId,
            final Long actorUserId,
            final UUID boardId,
            final NotificationType type,
            final String body) {
        this.tenantId = tenantId;
        this.recipientUserId = recipientUserId;
        this.actorUserId = actorUserId;
        this.boardId = boardId;
        this.type = type;
        this.body = body;
    }

    /** Sets {@code createdAt} to the current instant before the first insert if unset. */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /** @return the notification UUID */
    public UUID getId() {
        return id;
    }

    /** @return the tenant's {@code public.tenants.id} */
    public Long getTenantId() {
        return tenantId;
    }

    /** @return the recipient's {@code public.users.id} */
    public Long getRecipientUserId() {
        return recipientUserId;
    }

    /** @return the acting user's {@code public.users.id} */
    public Long getActorUserId() {
        return actorUserId;
    }

    /** @return the related board UUID, or {@code null} */
    public UUID getBoardId() {
        return boardId;
    }

    /** @return the notification type */
    public NotificationType getType() {
        return type;
    }

    /** @return the human-readable French body */
    public String getBody() {
        return body;
    }

    /** @return the creation timestamp */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /** @return the read timestamp, or {@code null} while unread */
    public Instant getReadAt() {
        return readAt;
    }
}
