package fr.pivot.collaboratif.whiteboard.board;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a whiteboard board.
 *
 * <p>Boards belong to a single tenant and always have one owner. The {@code visibility}
 * field defaults to {@link BoardVisibility#PRIVATE}. Timestamps are managed automatically
 * via JPA lifecycle callbacks.
 */
@Entity
@Table(name = "board", schema = "collaboratif")
public class Board {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Human-readable board title; maximum 100 characters enforced at the API layer. */
    @Column(name = "title", nullable = false, length = 100)
    private String title;

    /** Tenant that owns this board; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private UUID tenantId;

    /** User who created and owns this board. */
    @Column(name = "owner_id", nullable = false)
    private UUID ownerId;

    /** Visibility of the board; defaults to {@link BoardVisibility#PRIVATE}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "visibility", nullable = false, length = 20)
    private BoardVisibility visibility = BoardVisibility.PRIVATE;

    /** Timestamp when the board was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Board() {
    }

    /**
     * Full constructor for creating a new board with all fields.
     *
     * @param title    board title (max 100 chars)
     * @param tenantId owning tenant UUID
     * @param ownerId  creating user UUID
     * @param now      timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Board(
            final String title,
            final UUID tenantId,
            final UUID ownerId,
            final Instant now) {
        this.title = title;
        this.tenantId = tenantId;
        this.ownerId = ownerId;
        this.visibility = BoardVisibility.PRIVATE;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the board's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the board title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the board title.
     *
     * @param title the title to set
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant UUID
     */
    public UUID getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owner user identifier.
     *
     * @return the owner UUID
     */
    public UUID getOwnerId() {
        return ownerId;
    }

    /**
     * Returns the board visibility.
     *
     * @return the visibility
     */
    public BoardVisibility getVisibility() {
        return visibility;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last-updated timestamp (normally managed by {@link #preUpdate()}).
     *
     * @param updatedAt the instant to set
     */
    public void setUpdatedAt(final Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
